### ISSUE TITLE
filedata example fails

### ISSUE THREAD

**Issue by elinaawise** [apache/accumulo-examples#43]
This command produces the following error:

```sh
./bin/runmr filedata.CharacterHistogram -t dataTable --auths exampleVis --vis exampleVis
```

```java
Exception in thread "main" java.lang.IllegalStateException: Bad configuration: the store method was not called.
	at org.apache.accumulo.hadoopImpl.mapreduce.lib.ConfiguratorBase.checkJobStored(ConfiguratorBase.java:212)
	at org.apache.accumulo.hadoop.mapreduce.AccumuloOutputFormat.checkOutputSpecs(AccumuloOutputFormat.java:61)
	at org.apache.hadoop.mapreduce.JobSubmitter.checkSpecs(JobSubmitter.java:277)
	at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:143)
	at org.apache.hadoop.mapreduce.Job$11.run(Job.java:1570)
	at org.apache.hadoop.mapreduce.Job$11.run(Job.java:1567)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
	at org.apache.hadoop.mapreduce.Job.submit(Job.java:1567)
	at org.apache.hadoop.mapreduce.Job.waitForCompletion(Job.java:1588)
	at org.apache.accumulo.examples.filedata.CharacterHistogram.main(CharacterHistogram.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:323)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:236)
```

**Comment by jmark99** [comment]
The exception above can be corrected by updating the class to call the store method as needed. But this only leads to follow-on errors. There have been several methods updated between 1.10 and 2.x. Several methods have been deprecated as well. At this point the filedata example most likely should be re-factored to work with Accumulo 2.x.
