### ISSUE TITLE
Sample example java program fails with Accumulo-2.1.x

### ISSUE THREAD

**Issue by jmark99** [apache/accumulo-examples#65]
When run against the current Accumulo-2.1.0-SNAPSHOT, the java sample.SampleExample class fails with the following exception:

`Exception in thread "main" org.apache.accumulo.core.client.AccumuloException: TabletServer could not load CompactionStrategy class org.apache.accumulo.tserver.compaction.strategies.ConfigurableCompactionStrategy
        at org.apache.accumulo.core.clientImpl.TableOperationsImpl.ensureStrategyCanLoad(TableOperationsImpl.java:900)
        at org.apache.accumulo.core.clientImpl.TableOperationsImpl.compact(TableOperationsImpl.java:850)
        at org.apache.accumulo.examples.sample.SampleExample.main(SampleExample.java:105)`

The sample example works as expected if run step by step per directions. This error occurs only when executing the automated java program via the command:

`./bin/runex sample.SampleExample`

**Comment by DomGarguilo** [comment]
@jmark99, are you still planning to work this ticket? I think I may have a fix ready for this.

**Comment by jmark99** [comment]
@DomGarguilo I'll remove my assignment and let you ad your fix. Thanks.
