### ISSUE TITLE
Missing ZK class

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo-examples#69]
Running the ExamplesIT I am seeing this in the logs:
<pre>
java.lang.NoClassDefFoundError: org/apache/zookeeper/txn/TxnDigest
        at org.apache.zookeeper.server.PrepRequestProcessor.setTxnDigest(PrepRequestProcessor.java:1122) ~[zookeeper-3.6.2.jar:3.6.2]
        at org.apache.zookeeper.server.PrepRequestProcessor.pRequest2Txn(PrepRequestProcessor.java:645) ~[zookeeper-3.6.2.jar:3.6.2]
        at org.apache.zookeeper.server.PrepRequestProcessor.pRequest(PrepRequestProcessor.java:881) ~[zookeeper-3.6.2.jar:3.6.2]
        at org.apache.zookeeper.server.PrepRequestProcessor.run(PrepRequestProcessor.java:155) ~[zookeeper-3.6.2.jar:3.6.2]
Caused by: java.lang.ClassNotFoundException: org.apache.zookeeper.txn.TxnDigest
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 4 more
</pre>

**Comment by milleruntime** [comment]
@jmark99 Does your commit 02ab78f83df63f05ba1cefddafb622fe6a7b318f fix this NoClassDefFoundError?

**Comment by jmark99** [comment]
Not sure, as it has not been tested with the IT's yet. That was not the intention of the change. It was made just to keep the examples repo and primary repo in line with one another. I will update the comments here once I attempt to run the IT's.

**Comment by milleruntime** [comment]
OK well it looks like that is the case so I will close this as fixed.
