### ISSUE TITLE
ClassNotFoundException on several examples

### ISSUE THREAD

**Issue by DomGarguilo** [apache/accumulo-examples#95]
When running the dirlist, filedata and possibly other examples, the following error occurs in the monitor.

```
java.lang.RuntimeException: java.lang.ClassNotFoundException: org.apache.accumulo.examples.filedata.ChunkCombiner
	at org.apache.accumulo.core.conf.IterConfigUtil.loadIterators(IterConfigUtil.java:226)
	at org.apache.accumulo.core.conf.IterConfigUtil.convertItersAndLoad(IterConfigUtil.java:188)
	at org.apache.accumulo.server.compaction.FileCompactor.compactLocalityGroup(FileCompactor.java:362)
	at org.apache.accumulo.server.compaction.FileCompactor.call(FileCompactor.java:230)
	at org.apache.accumulo.tserver.tablet.MinorCompactor.call(MinorCompactor.java:95)
	at org.apache.accumulo.tserver.tablet.Tablet.minorCompact(Tablet.java:813)
	at org.apache.accumulo.tserver.tablet.MinorCompactionTask.run(MinorCompactionTask.java:110)
	at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: org.apache.accumulo.examples.filedata.ChunkCombiner
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at org.apache.accumulo.start.classloader.AccumuloClassLoader$1.loadClass(AccumuloClassLoader.java:213)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.apache.accumulo.core.classloader.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:85)
	at org.apache.accumulo.core.conf.IterConfigUtil.loadClass(IterConfigUtil.java:236)
	at org.apache.accumulo.core.conf.IterConfigUtil.loadIterators(IterConfigUtil.java:211)
	... 11 more
```
There is the following note in the filedata example:
```
Note that in order to scan the 
examples.dataTable the class, org.apache.accumulo.examples.filedata.ChunkCombiner, must be in 
your classpath, or the accumulo-examples-shaded.jar should be moved to the accumulo lib directory.
```
This error occurs even with the shaded jar moved to the lib directory.

To reproduce: follow the steps on either the dirlist or filedata examples and check the monitor for errors.

**Comment by dlmarion** [comment]
Just curious, was the shaded jar moved to the `lib` directory *before* Accumulo was started?

**Comment by DomGarguilo** [comment]
> Just curious, was the shaded jar moved to the `lib` directory _before_ Accumulo was started?

That might be causing the issue I'm seeing. I was initially moving the jars after accumulo was started which is probably what was causing the error. For some odd reason I cannot get a tserver to start correctly once the shaded jar has been copied into /lib using fluo-uno. Regardless, that is outside of the scope of this ticket so I'll close it for now.
